import Head from "next/head";
import Hero from "../components/Hero";
import Homearea from "../components/Homearea";
import Navbar from "../components/Navbar";
import RotatingImage from "../components/RotatingImage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Razor Edge Studio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      {/* <Hero /> */}
      {/* <RotatingImage /> */}
      <Homearea />
    </div>
  );
}
